<?php

use Illuminate\Database\Seeder;
use App\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            [
                "country_code" => "AD",
                "lat" => 42.546245,
                "long" => 1.601554,
                "country" => "Andorra",
            ],
            [
                "country_code" => "AE",
                "lat" => 23.424076,
                "long" => 53.847818,
                "country" => "United Arab Emirates",
            ],
            [
                "country_code" => "AF",
                "lat" => 33.93911,
                "long" => 67.709953,
                "country" => "Afghanistan",
            ],
            [
                "country_code" => "AG",
                "lat" => 17.060816,
                "long" => -61.796428,
                "country" => "Antigua and Barbuda",
            ],
            [
                "country_code" => "AI",
                "lat" => 18.220554,
                "long" => -63.068615,
                "country" => "Anguilla",
            ],
            [
                "country_code" => "AL",
                "lat" => 41.153332,
                "long" => 20.168331,
                "country" => "Albania",
            ],
            [
                "country_code" => "AM",
                "lat" => 40.069099,
                "long" => 45.038189,
                "country" => "Armenia",
            ],
            [
                "country_code" => "AN",
                "lat" => 12.226079,
                "long" => -69.060087,
                "country" => "Netherlands Antilles",
            ],
            [
                "country_code" => "AO",
                "lat" => -11.202692,
                "long" => 17.873887,
                "country" => "Angola",
            ],
            [
                "country_code" => "AQ",
                "lat" => -75.250973,
                "long" => -0.071389,
                "country" => "Antarctica",
            ],
            [
                "country_code" => "AR",
                "lat" => -38.416097,
                "long" => -63.616672,
                "country" => "Argentina",
            ],
            [
                "country_code" => "AS",
                "lat" => -14.270972,
                "long" => -170.132217,
                "country" => "American Samoa",
            ],
            [
                "country_code" => "AT",
                "lat" => 47.516231,
                "long" => 14.550072,
                "country" => "Austria",
            ],
            [
                "country_code" => "AU",
                "lat" => -25.274398,
                "long" => 133.775136,
                "country" => "Australia",
            ],
            [
                "country_code" => "AW",
                "lat" => 12.52111,
                "long" => -69.968338,
                "country" => "Aruba",
            ],
            [
                "country_code" => "AZ",
                "lat" => 40.143105,
                "long" => 47.576927,
                "country" => "Azerbaijan",
            ],
            [
                "country_code" => "BA",
                "lat" => 43.915886,
                "long" => 17.679076,
                "country" => "Bosnia and Herzegovina",
            ],
            [
                "country_code" => "BB",
                "lat" => 13.193887,
                "long" => -59.543198,
                "country" => "Barbados",
            ],
            [
                "country_code" => "BD",
                "lat" => 23.684994,
                "long" => 90.356331,
                "country" => "Bangladesh",
            ],
            [
                "country_code" => "BE",
                "lat" => 50.503887,
                "long" => 4.469936,
                "country" => "Belgium",
            ],
            [
                "country_code" => "BF",
                "lat" => 12.238333,
                "long" => -1.561593,
                "country" => "Burkina Faso",
            ],
            [
                "country_code" => "BG",
                "lat" => 42.733883,
                "long" => 25.48583,
                "country" => "Bulgaria",
            ],
            [
                "country_code" => "BH",
                "lat" => 25.930414,
                "long" => 50.637772,
                "country" => "Bahrain",
            ],
            [
                "country_code" => "BI",
                "lat" => -3.373056,
                "long" => 29.918886,
                "country" => "Burundi",
            ],
            [
                "country_code" => "BJ",
                "lat" => 9.30769,
                "long" => 2.315834,
                "country" => "Benin",
            ],
            [
                "country_code" => "BM",
                "lat" => 32.321384,
                "long" => -64.75737,
                "country" => "Bermuda",
            ],
            [
                "country_code" => "BN",
                "lat" => 4.535277,
                "long" => 114.727669,
                "country" => "Brunei",
            ],
            [
                "country_code" => "BO",
                "lat" => -16.290154,
                "long" => -63.588653,
                "country" => "Bolivia",
            ],
            [
                "country_code" => "BR",
                "lat" => -14.235004,
                "long" => -51.92528,
                "country" => "Brazil",
            ],
            [
                "country_code" => "BS",
                "lat" => 25.03428,
                "long" => -77.39628,
                "country" => "Bahamas",
            ],
            [
                "country_code" => "BT",
                "lat" => 27.514162,
                "long" => 90.433601,
                "country" => "Bhutan",
            ],
            [
                "country_code" => "BV",
                "lat" => -54.423199,
                "long" => 3.413194,
                "country" => "Bouvet Island",
            ],
            [
                "country_code" => "BW",
                "lat" => -22.328474,
                "long" => 24.684866,
                "country" => "Botswana",
            ],
            [
                "country_code" => "BY",
                "lat" => 53.709807,
                "long" => 27.953389,
                "country" => "Belarus",
            ],
            [
                "country_code" => "BZ",
                "lat" => 17.189877,
                "long" => -88.49765,
                "country" => "Belize",
            ],
            [
                "country_code" => "CA",
                "lat" => 56.130366,
                "long" => -106.346771,
                "country" => "Canada",
            ],
            [
                "country_code" => "CC",
                "lat" => -12.164165,
                "long" => 96.870956,
                "country" => "Cocos Islands",
            ],
            [
                "country_code" => "CD",
                "lat" => -4.038333,
                "long" => 21.758664,
                "country" => "Congo",
            ],
            [
                "country_code" => "CF",
                "lat" => 6.611111,
                "long" => 20.939444,
                "country" => "Central African Republic",
            ],
            [
                "country_code" => "CG",
                "lat" => -0.228021,
                "long" => 15.827659,
                "country" => "Congo",
            ],
            [
                "country_code" => "CH",
                "lat" => 46.818188,
                "long" => 8.227512,
                "country" => "Switzerland",
            ],
            [
                "country_code" => "CI",
                "lat" => 7.539989,
                "long" => -5.54708,
                "country" => "Côte d'Ivoire",
            ],
            [
                "country_code" => "CK",
                "lat" => -21.236736,
                "long" => -159.777671,
                "country" => "Cook Islands",
            ],
            [
                "country_code" => "CL",
                "lat" => -35.675147,
                "long" => -71.542969,
                "country" => "Chile",
            ],
            [
                "country_code" => "CM",
                "lat" => 7.369722,
                "long" => 12.354722,
                "country" => "Cameroon",
            ],
            [
                "country_code" => "CN",
                "lat" => 35.86166,
                "long" => 104.195397,
                "country" => "China",
            ],
            [
                "country_code" => "CO",
                "lat" => 4.570868,
                "long" => -74.297333,
                "country" => "Colombia",
            ],
            [
                "country_code" => "CR",
                "lat" => 9.748917,
                "long" => -83.753428,
                "country" => "Costa Rica",
            ],
            [
                "country_code" => "CU",
                "lat" => 21.521757,
                "long" => -77.781167,
                "country" => "Cuba",
            ],
            [
                "country_code" => "CV",
                "lat" => 16.002082,
                "long" => -24.013197,
                "country" => "Cape Verde",
            ],
            [
                "country_code" => "CX",
                "lat" => -10.447525,
                "long" => 105.690449,
                "country" => "Christmas Island",
            ],
            [
                "country_code" => "CY",
                "lat" => 35.126413,
                "long" => 33.429859,
                "country" => "Cyprus",
            ],
            [
                "country_code" => "CZ",
                "lat" => 49.817492,
                "long" => 15.472962,
                "country" => "Czech Republic",
            ],
            [
                "country_code" => "DE",
                "lat" => 51.165691,
                "long" => 10.451526,
                "country" => "Germany",
            ],
            [
                "country_code" => "DJ",
                "lat" => 11.825138,
                "long" => 42.590275,
                "country" => "Djibouti",
            ],
            [
                "country_code" => "DK",
                "lat" => 56.26392,
                "long" => 9.501785,
                "country" => "Denmark",
            ],
            [
                "country_code" => "DM",
                "lat" => 15.414999,
                "long" => -61.370976,
                "country" => "Dominica",
            ],
            [
                "country_code" => "DO",
                "lat" => 18.735693,
                "long" => -70.162651,
                "country" => "Dominican Republic",
            ],
            [
                "country_code" => "DZ",
                "lat" => 28.033886,
                "long" => 1.659626,
                "country" => "Algeria",
            ],
            [
                "country_code" => "EC",
                "lat" => -1.831239,
                "long" => -78.183406,
                "country" => "Ecuador",
            ],
            [
                "country_code" => "EE",
                "lat" => 58.595272,
                "long" => 25.013607,
                "country" => "Estonia",
            ],
            [
                "country_code" => "EG",
                "lat" => 26.820553,
                "long" => 30.802498,
                "country" => "Egypt",
            ],
            [
                "country_code" => "EH",
                "lat" => 24.215527,
                "long" => -12.885834,
                "country" => "Western Sahara",
            ],
            [
                "country_code" => "ER",
                "lat" => 15.179384,
                "long" => 39.782334,
                "country" => "Eritrea",
            ],
            [
                "country_code" => "ES",
                "lat" => 40.463667,
                "long" => -3.74922,
                "country" => "Spain",
            ],
            [
                "country_code" => "ET",
                "lat" => 9.145,
                "long" => 40.489673,
                "country" => "Ethiopia",
            ],
            [
                "country_code" => "FI",
                "lat" => 61.92411,
                "long" => 25.748151,
                "country" => "Finland",
            ],
            [
                "country_code" => "FJ",
                "lat" => -16.578193,
                "long" => 179.414413,
                "country" => "Fiji",
            ],
            [
                "country_code" => "FK",
                "lat" => -51.796253,
                "long" => -59.523613,
                "country" => "Falkland Islands",
            ],
            [
                "country_code" => "FM",
                "lat" => 7.425554,
                "long" => 150.550812,
                "country" => "Micronesia",
            ],
            [
                "country_code" => "FO",
                "lat" => 61.892635,
                "long" => -6.911806,
                "country" => "Faroe Islands",
            ],
            [
                "country_code" => "FR",
                "lat" => 46.227638,
                "long" => 2.213749,
                "country" => "France",
            ],
            [
                "country_code" => "GA",
                "lat" => -0.803689,
                "long" => 11.609444,
                "country" => "Gabon",
            ],
            [
                "country_code" => "GB",
                "lat" => 55.378051,
                "long" => -3.435973,
                "country" => "United Kingdom",
            ],
            [
                "country_code" => "GD",
                "lat" => 12.262776,
                "long" => -61.604171,
                "country" => "Grenada",
            ],
            [
                "country_code" => "GE",
                "lat" => 42.315407,
                "long" => 43.356892,
                "country" => "Georgia",
            ],
            [
                "country_code" => "GF",
                "lat" => 3.933889,
                "long" => -53.125782,
                "country" => "French Guiana",
            ],
            [
                "country_code" => "GG",
                "lat" => 49.465691,
                "long" => -2.585278,
                "country" => "Guernsey",
            ],
            [
                "country_code" => "GH",
                "lat" => 7.946527,
                "long" => -1.023194,
                "country" => "Ghana",
            ],
            [
                "country_code" => "GI",
                "lat" => 36.137741,
                "long" => -5.345374,
                "country" => "Gibraltar",
            ],
            [
                "country_code" => "GL",
                "lat" => 71.706936,
                "long" => -42.604303,
                "country" => "Greenland",
            ],
            [
                "country_code" => "GM",
                "lat" => 13.443182,
                "long" => -15.310139,
                "country" => "Gambia",
            ],
            [
                "country_code" => "GN",
                "lat" => 9.945587,
                "long" => -9.696645,
                "country" => "Guinea",
            ],
            [
                "country_code" => "GP",
                "lat" => 16.995971,
                "long" => -62.067641,
                "country" => "Guadeloupe",
            ],
            [
                "country_code" => "GQ",
                "lat" => 1.650801,
                "long" => 10.267895,
                "country" => "Equatorial Guinea",
            ],
            [
                "country_code" => "GR",
                "lat" => 39.074208,
                "long" => 21.824312,
                "country" => "Greece",
            ],
            [
                "country_code" => "GS",
                "lat" => -54.429579,
                "long" => -36.587909,
                "country" => "South Georgia and the South Sandwich Islands",
            ],
            [
                "country_code" => "GT",
                "lat" => 15.783471,
                "long" => -90.230759,
                "country" => "Guatemala",
            ],
            [
                "country_code" => "GU",
                "lat" => 13.444304,
                "long" => 144.793731,
                "country" => "Guam",
            ],
            [
                "country_code" => "GW",
                "lat" => 11.803749,
                "long" => -15.180413,
                "country" => "Guinea-Bissau",
            ],
            [
                "country_code" => "GY",
                "lat" => 4.860416,
                "long" => -58.93018,
                "country" => "Guyana",
            ],
            [
                "country_code" => "GZ",
                "lat" => 31.354676,
                "long" => 34.308825,
                "country" => "Gaza Strip",
            ],
            [
                "country_code" => "HK",
                "lat" => 22.396428,
                "long" => 114.109497,
                "country" => "Hong Kong",
            ],
            [
                "country_code" => "HM",
                "lat" => -53.08181,
                "long" => 73.504158,
                "country" => "Heard Island and McDonald Islands",
            ],
            [
                "country_code" => "HN",
                "lat" => 15.199999,
                "long" => -86.241905,
                "country" => "Honduras",
            ],
            [
                "country_code" => "HR",
                "lat" => 45.1,
                "long" => 15.2,
                "country" => "Croatia",
            ],
            [
                "country_code" => "HT",
                "lat" => 18.971187,
                "long" => -72.285215,
                "country" => "Haiti",
            ],
            [
                "country_code" => "HU",
                "lat" => 47.162494,
                "long" => 19.503304,
                "country" => "Hungary",
            ],
            [
                "country_code" => "ID",
                "lat" => -0.789275,
                "long" => 113.921327,
                "country" => "Indonesia",
            ],
            [
                "country_code" => "IE",
                "lat" => 53.41291,
                "long" => -8.24389,
                "country" => "Ireland",
            ],
            [
                "country_code" => "IL",
                "lat" => 31.046051,
                "long" => 34.851612,
                "country" => "Israel",
            ],
            [
                "country_code" => "IM",
                "lat" => 54.236107,
                "long" => -4.548056,
                "country" => "Isle of Man",
            ],
            [
                "country_code" => "IN",
                "lat" => 20.593684,
                "long" => 78.96288,
                "country" => "India",
            ],
            [
                "country_code" => "IO",
                "lat" => -6.343194,
                "long" => 71.876519,
                "country" => "British Indian Ocean Territory",
            ],
            [
                "country_code" => "IQ",
                "lat" => 33.223191,
                "long" => 43.679291,
                "country" => "Iraq",
            ],
            [
                "country_code" => "IR",
                "lat" => 32.427908,
                "long" => 53.688046,
                "country" => "Iran",
            ],
            [
                "country_code" => "IS",
                "lat" => 64.963051,
                "long" => -19.020835,
                "country" => "Iceland",
            ],
            [
                "country_code" => "IT",
                "lat" => 41.87194,
                "long" => 12.56738,
                "country" => "Italy",
            ],
            [
                "country_code" => "JE",
                "lat" => 49.214439,
                "long" => -2.13125,
                "country" => "Jersey",
            ],
            [
                "country_code" => "JM",
                "lat" => 18.109581,
                "long" => -77.297508,
                "country" => "Jamaica",
            ],
            [
                "country_code" => "JO",
                "lat" => 30.585164,
                "long" => 36.238414,
                "country" => "Jordan",
            ],
            [
                "country_code" => "JP",
                "lat" => 36.204824,
                "long" => 138.252924,
                "country" => "Japan",
            ],
            [
                "country_code" => "KE",
                "lat" => -0.023559,
                "long" => 37.906193,
                "country" => "Kenya",
            ],
            [
                "country_code" => "KG",
                "lat" => 41.20438,
                "long" => 74.766098,
                "country" => "Kyrgyzstan",
            ],
            [
                "country_code" => "KH",
                "lat" => 12.565679,
                "long" => 104.990963,
                "country" => "Cambodia",
            ],
            [
                "country_code" => "KI",
                "lat" => -3.370417,
                "long" => -168.734039,
                "country" => "Kiribati",
            ],
            [
                "country_code" => "KM",
                "lat" => -11.875001,
                "long" => 43.872219,
                "country" => "Comoros",
            ],
            [
                "country_code" => "KN",
                "lat" => 17.357822,
                "long" => -62.782998,
                "country" => "Saint Kitts and Nevis",
            ],
            [
                "country_code" => "KP",
                "lat" => 40.339852,
                "long" => 127.510093,
                "country" => "North Korea",
            ],
            [
                "country_code" => "KR",
                "lat" => 35.907757,
                "long" => 127.766922,
                "country" => "South Korea",
            ],
            [
                "country_code" => "KW",
                "lat" => 29.31166,
                "long" => 47.481766,
                "country" => "Kuwait",
            ],
            [
                "country_code" => "KY",
                "lat" => 19.513469,
                "long" => -80.566956,
                "country" => "Cayman Islands",
            ],
            [
                "country_code" => "KZ",
                "lat" => 48.019573,
                "long" => 66.923684,
                "country" => "Kazakhstan",
            ],
            [
                "country_code" => "LA",
                "lat" => 19.85627,
                "long" => 102.495496,
                "country" => "Laos",
            ],
            [
                "country_code" => "LB",
                "lat" => 33.854721,
                "long" => 35.862285,
                "country" => "Lebanon",
            ],
            [
                "country_code" => "LC",
                "lat" => 13.909444,
                "long" => -60.978893,
                "country" => "Saint Lucia",
            ],
            [
                "country_code" => "LI",
                "lat" => 47.166,
                "long" => 9.555373,
                "country" => "Liechtenstein",
            ],
            [
                "country_code" => "LK",
                "lat" => 7.873054,
                "long" => 80.771797,
                "country" => "Sri Lanka",
            ],
            [
                "country_code" => "LR",
                "lat" => 6.428055,
                "long" => -9.429499,
                "country" => "Liberia",
            ],
            [
                "country_code" => "LS",
                "lat" => -29.609988,
                "long" => 28.233608,
                "country" => "Lesotho",
            ],
            [
                "country_code" => "LT",
                "lat" => 55.169438,
                "long" => 23.881275,
                "country" => "Lithuania",
            ],
            [
                "country_code" => "LU",
                "lat" => 49.815273,
                "long" => 6.129583,
                "country" => "Luxembourg",
            ],
            [
                "country_code" => "LV",
                "lat" => 56.879635,
                "long" => 24.603189,
                "country" => "Latvia",
            ],
            [
                "country_code" => "LY",
                "lat" => 26.3351,
                "long" => 17.228331,
                "country" => "Libya",
            ],
            [
                "country_code" => "MA",
                "lat" => 31.791702,
                "long" => -7.09262,
                "country" => "Morocco",
            ],
            [
                "country_code" => "MC",
                "lat" => 43.750298,
                "long" => 7.412841,
                "country" => "Monaco",
            ],
            [
                "country_code" => "MD",
                "lat" => 47.411631,
                "long" => 28.369885,
                "country" => "Moldova",
            ],
            [
                "country_code" => "ME",
                "lat" => 42.708678,
                "long" => 19.37439,
                "country" => "Montenegro",
            ],
            [
                "country_code" => "MG",
                "lat" => -18.766947,
                "long" => 46.869107,
                "country" => "Madagascar",
            ],
            [
                "country_code" => "MH",
                "lat" => 7.131474,
                "long" => 171.184478,
                "country" => "Marshall Islands",
            ],
            [
                "country_code" => "MK",
                "lat" => 41.608635,
                "long" => 21.745275,
                "country" => "Macedonia",
            ],
            [
                "country_code" => "ML",
                "lat" => 17.570692,
                "long" => -3.996166,
                "country" => "Mali",
            ],
            [
                "country_code" => "MM",
                "lat" => 21.913965,
                "long" => 95.956223,
                "country" => "Myanmar",
            ],
            [
                "country_code" => "MN",
                "lat" => 46.862496,
                "long" => 103.846656,
                "country" => "Mongolia",
            ],
            [
                "country_code" => "MO",
                "lat" => 22.198745,
                "long" => 113.543873,
                "country" => "Macau",
            ],
            [
                "country_code" => "MP",
                "lat" => 17.33083,
                "long" => 145.38469,
                "country" => "Northern Mariana Islands",
            ],
            [
                "country_code" => "MQ",
                "lat" => 14.641528,
                "long" => -61.024174,
                "country" => "Martinique",
            ],
            [
                "country_code" => "MR",
                "lat" => 21.00789,
                "long" => -10.940835,
                "country" => "Mauritania",
            ],
            [
                "country_code" => "MS",
                "lat" => 16.742498,
                "long" => -62.187366,
                "country" => "Montserrat",
            ],
            [
                "country_code" => "MT",
                "lat" => 35.937496,
                "long" => 14.375416,
                "country" => "Malta",
            ],
            [
                "country_code" => "MU",
                "lat" => -20.348404,
                "long" => 57.552152,
                "country" => "Mauritius",
            ],
            [
                "country_code" => "MV",
                "lat" => 3.202778,
                "long" => 73.22068,
                "country" => "Maldives",
            ],
            [
                "country_code" => "MW",
                "lat" => -13.254308,
                "long" => 34.301525,
                "country" => "Malawi",
            ],
            [
                "country_code" => "MX",
                "lat" => 23.634501,
                "long" => -102.552784,
                "country" => "Mexico",
            ],
            [
                "country_code" => "MY",
                "lat" => 4.210484,
                "long" => 101.975766,
                "country" => "Malaysia",
            ],
            [
                "country_code" => "MZ",
                "lat" => -18.665695,
                "long" => 35.529562,
                "country" => "Mozambique",
            ],
            [
                "country_code" => "NA",
                "lat" => -22.95764,
                "long" => 18.49041,
                "country" => "Namibia",
            ],
            [
                "country_code" => "NC",
                "lat" => -20.904305,
                "long" => 165.618042,
                "country" => "New Caledonia",
            ],
            [
                "country_code" => "NE",
                "lat" => 17.607789,
                "long" => 8.081666,
                "country" => "Niger",
            ],
            [
                "country_code" => "NF",
                "lat" => -29.040835,
                "long" => 167.954712,
                "country" => "Norfolk Island",
            ],
            [
                "country_code" => "NG",
                "lat" => 9.081999,
                "long" => 8.675277,
                "country" => "Nigeria",
            ],
            [
                "country_code" => "NI",
                "lat" => 12.865416,
                "long" => -85.207229,
                "country" => "Nicaragua",
            ],
            [
                "country_code" => "NL",
                "lat" => 52.132633,
                "long" => 5.291266,
                "country" => "Netherlands",
            ],
            [
                "country_code" => "NO",
                "lat" => 60.472024,
                "long" => 8.468946,
                "country" => "Norway",
            ],
            [
                "country_code" => "NP",
                "lat" => 28.394857,
                "long" => 84.124008,
                "country" => "Nepal",
            ],
            [
                "country_code" => "NR",
                "lat" => -0.522778,
                "long" => 166.931503,
                "country" => "Nauru",
            ],
            [
                "country_code" => "NU",
                "lat" => -19.054445,
                "long" => -169.867233,
                "country" => "Niue",
            ],
            [
                "country_code" => "NZ",
                "lat" => -40.900557,
                "long" => 174.885971,
                "country" => "New Zealand",
            ],
            [
                "country_code" => "OM",
                "lat" => 21.512583,
                "long" => 55.923255,
                "country" => "Oman",
            ], [
                "country_code" => "PA",
                "lat" => 8.537981,
                "long" => -80.782127,
                "country" => "Panama",
            ],
            [
                "country_code" => "PE",
                "lat" => -9.189967,
                "long" => -75.015152,
                "country" => "Peru",
            ],
            [
                "country_code" => "PF",
                "lat" => -17.679742,
                "long" => -149.406843,
                "country" => "French Polynesia",
            ],
            [
                "country_code" => "PG",
                "lat" => -6.314993,
                "long" => 143.95555,
                "country" => "Papua New Guinea",
            ],
            [
                "country_code" => "PH",
                "lat" => 12.879721,
                "long" => 121.774017,
                "country" => "Philippines",
            ],
            [
                "country_code" => "PK",
                "lat" => 30.375321,
                "long" => 69.345116,
                "country" => "Pakistan",
            ],
            [
                "country_code" => "PL",
                "lat" => 51.919438,
                "long" => 19.145136,
                "country" => "Poland",
            ],
            [
                "country_code" => "PM",
                "lat" => 46.941936,
                "long" => -56.27111,
                "country" => "Saint Pierre and Miquelon",
            ],
            [
                "country_code" => "PN",
                "lat" => -24.703615,
                "long" => -127.439308,
                "country" => "Pitcairn Islands",
            ],
            [
                "country_code" => "PR",
                "lat" => 18.220833,
                "long" => -66.590149,
                "country" => "Puerto Rico",
            ],
            [
                "country_code" => "PS",
                "lat" => 31.952162,
                "long" => 35.233154,
                "country" => "Palestinian Territories",
            ],
            [
                "country_code" => "PT",
                "lat" => 39.399872,
                "long" => -8.224454,
                "country" => "Portugal",
            ],
            [
                "country_code" => "PW",
                "lat" => 7.51498,
                "long" => 134.58252,
                "country" => "Palau",
            ],
            [
                "country_code" => "PY",
                "lat" => -23.442503,
                "long" => -58.443832,
                "country" => "Paraguay",
            ],
            [
                "country_code" => "QA",
                "lat" => 25.354826,
                "long" => 51.183884,
                "country" => "Qatar",
            ],
            [
                "country_code" => "RE",
                "lat" => -21.115141,
                "long" => 55.536384,
                "country" => "Réunion",
            ],
            [
                "country_code" => "RO",
                "lat" => 45.943161,
                "long" => 24.96676,
                "country" => "Romania",
            ],
            [
                "country_code" => "RS",
                "lat" => 44.016521,
                "long" => 21.005859,
                "country" => "Serbia",
            ],
            [
                "country_code" => "RU",
                "lat" => 61.52401,
                "long" => 105.318756,
                "country" => "Russia",
            ],
            [
                "country_code" => "RW",
                "lat" => -1.940278,
                "long" => 29.873888,
                "country" => "Rwanda",
            ],
            [
                "country_code" => "SA",
                "lat" => 23.885942,
                "long" => 45.079162,
                "country" => "Saudi Arabia",
            ],
            [
                "country_code" => "SB",
                "lat" => -9.64571,
                "long" => 160.156194,
                "country" => "Solomon Islands",
            ],
            [
                "country_code" => "SC",
                "lat" => -4.679574,
                "long" => 55.491977,
                "country" => "Seychelles",
            ],
            [
                "country_code" => "SD",
                "lat" => 12.862807,
                "long" => 30.217636,
                "country" => "Sudan",
            ],
            [
                "country_code" => "SE",
                "lat" => 60.128161,
                "long" => 18.643501,
                "country" => "Sweden",
            ],
            [
                "country_code" => "SG",
                "lat" => 1.352083,
                "long" => 103.819836,
                "country" => "Singapore",
            ],
            [
                "country_code" => "SH",
                "lat" => -24.143474,
                "long" => -10.030696,
                "country" => "Saint Helena",
            ],
            [
                "country_code" => "SI",
                "lat" => 46.151241,
                "long" => 14.995463,
                "country" => "Slovenia",
            ],
            [
                "country_code" => "SJ",
                "lat" => 77.553604,
                "long" => 23.670272,
                "country" => "Svalbard and Jan Mayen",
            ],
            [
                "country_code" => "SK",
                "lat" => 48.669026,
                "long" => 19.699024,
                "country" => "Slovakia",
            ],
            [
                "country_code" => "SL",
                "lat" => 8.460555,
                "long" => -11.779889,
                "country" => "Sierra Leone",
            ],
            [
                "country_code" => "SM",
                "lat" => 43.94236,
                "long" => 12.457777,
                "country" => "San Marino",
            ],
            [
                "country_code" => "SN",
                "lat" => 14.497401,
                "long" => -14.452362,
                "country" => "Senegal",
            ],
            [
                "country_code" => "SO",
                "lat" => 5.152149,
                "long" => 46.199616,
                "country" => "Somalia",
            ],
            [
                "country_code" => "SR",
                "lat" => 3.919305,
                "long" => -56.027783,
                "country" => "Suriname",
            ],
            [
                "country_code" => "ST",
                "lat" => 0.18636,
                "long" => 6.613081,
                "country" => "São Tomé and Príncipe",
            ],
            [
                "country_code" => "SV",
                "lat" => 13.794185,
                "long" => -88.89653,
                "country" => "El Salvador",
            ],
            [
                "country_code" => "SY",
                "lat" => 34.802075,
                "long" => 38.996815,
                "country" => "Syria",
            ],
            [
                "country_code" => "SZ",
                "lat" => -26.522503,
                "long" => 31.465866,
                "country" => "Swaziland",
            ],
            [
                "country_code" => "TC",
                "lat" => 21.694025,
                "long" => -71.797928,
                "country" => "Turks and Caicos Islands",
            ],
            [
                "country_code" => "TD",
                "lat" => 15.454166,
                "long" => 18.732207,
                "country" => "Chad",
            ],
            [
                "country_code" => "TF",
                "lat" => -49.280366,
                "long" => 69.348557,
                "country" => "French Southern Territories",
            ],
            [
                "country_code" => "TG",
                "lat" => 8.619543,
                "long" => 0.824782,
                "country" => "Togo",
            ],
            [
                "country_code" => "TH",
                "lat" => 15.870032,
                "long" => 100.992541,
                "country" => "Thailand",
            ],
            [
                "country_code" => "TJ",
                "lat" => 38.861034,
                "long" => 71.276093,
                "country" => "Tajikistan",
            ],
            [
                "country_code" => "TK",
                "lat" => -8.967363,
                "long" => -171.855881,
                "country" => "Tokelau",
            ],
            [
                "country_code" => "TL",
                "lat" => -8.874217,
                "long" => 125.727539,
                "country" => "Timor-Leste",
            ],
            [
                "country_code" => "TM",
                "lat" => 38.969719,
                "long" => 59.556278,
                "country" => "Turkmenistan",
            ],
            [
                "country_code" => "TN",
                "lat" => 33.886917,
                "long" => 9.537499,
                "country" => "Tunisia",
            ],
            [
                "country_code" => "TO",
                "lat" => -21.178986,
                "long" => -175.198242,
                "country" => "Tonga",
            ],
            [
                "country_code" => "TR",
                "lat" => 38.963745,
                "long" => 35.243322,
                "country" => "Turkey",
            ],
            [
                "country_code" => "TT",
                "lat" => 10.691803,
                "long" => -61.222503,
                "country" => "Trinidad and Tobago",
            ],
            [
                "country_code" => "TV",
                "lat" => -7.109535,
                "long" => 177.64933,
                "country" => "Tuvalu",
            ],
            [
                "country_code" => "TW",
                "lat" => 23.69781,
                "long" => 120.960515,
                "country" => "Taiwan",
            ],
            [
                "country_code" => "TZ",
                "lat" => -6.369028,
                "long" => 34.888822,
                "country" => "Tanzania",
            ],
            [
                "country_code" => "UA",
                "lat" => 48.379433,
                "long" => 31.16558,
                "country" => "Ukraine",
            ],
            [
                "country_code" => "UG",
                "lat" => 1.373333,
                "long" => 32.290275,
                "country" => "Uganda",
            ],
            [
                "country_code" => "US",
                "lat" => 37.09024,
                "long" => -95.712891,
                "country" => "United States",
            ],
            [
                "country_code" => "UY",
                "lat" => -32.522779,
                "long" => -55.765835,
                "country" => "Uruguay",
            ],
            [
                "country_code" => "UZ",
                "lat" => 41.377491,
                "long" => 64.585262,
                "country" => "Uzbekistan",
            ],
            [
                "country_code" => "VA",
                "lat" => 41.902916,
                "long" => 12.453389,
                "country" => "Vatican City",
            ],
            [
                "country_code" => "VC",
                "lat" => 12.984305,
                "long" => -61.287228,
                "country" => "Saint Vincent and the Grenadines",
            ],
            [
                "country_code" => "VE",
                "lat" => 6.42375,
                "long" => -66.58973,
                "country" => "Venezuela",
            ],
            [
                "country_code" => "VG",
                "lat" => 18.420695,
                "long" => -64.639968,
                "country" => "British Virgin Islands",
            ],
            [
                "country_code" => "VI",
                "lat" => 18.335765,
                "long" => -64.896335,
                "country" => "U.S. Virgin Islands",
            ],
            [
                "country_code" => "VN",
                "lat" => 14.058324,
                "long" => 108.277199,
                "country" => "Vietnam",
            ],
            [
                "country_code" => "VU",
                "lat" => -15.376706,
                "long" => 166.959158,
                "country" => "Vanuatu",
            ],
            [
                "country_code" => "WF",
                "lat" => -13.768752,
                "long" => -177.156097,
                "country" => "Wallis and Futuna",
            ],
            [
                "country_code" => "WS",
                "lat" => -13.759029,
                "long" => -172.104629,
                "country" => "Samoa",
            ],
            [
                "country_code" => "XK",
                "lat" => 42.602636,
                "long" => 20.902977,
                "country" => "Kosovo",
            ],
            [
                "country_code" => "YE",
                "lat" => 15.552727,
                "long" => 48.516388,
                "country" => "Yemen",
            ],
            [
                "country_code" => "YT",
                "lat" => -12.8275,
                "long" => 45.166244,
                "country" => "Mayotte",
            ],
            [
                "country_code" => "ZA",
                "lat" => -30.559482,
                "long" => 22.937506,
                "country" => "South Africa",
            ],
            [
                "country_code" => "ZM",
                "lat" => -13.133897,
                "long" => 27.849332,
                "country" => "Zambia",
            ],
            [
                "country_code" => "ZW",
                "lat" => -19.015438,
                "long" => 29.154857,
                "country" => "Zimbabwe",
            ],
        ];
    }
}
